workflows:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**/*'

scripts:
  - changed-files:
      - any-glob-to-any-file: 'scripts/**/*'

# Add 'ENV' label if .env.example file gets modified
ENV:
  - changed-files:
      - any-glob-to-any-file: '.env.example'

# Add 'Package' label if Package.json file gets modified
Package:
  - changed-files:
      - any-glob-to-any-file: '.package.json'

# Add 'Config' label to any change to src files within the source dir EXCEPT for the docs sub-folder
Config:
  - changed-files:
      - any-glob-to-any-file: 'src/config/*'

# Add 'Validations' label to any change to src files within the source dir.
Validations:
  - changed-files:
      - any-glob-to-any-file: 'src/validations/*'

# Add 'root' label to any root file changes 
root:
- all:
  - changed-files:
    - any-glob-to-any-file: '*'
    - all-globs-to-all-files: ['!src/*']


# Add 'Documentation' label to any changes within 'routes' folder or any subfolders or in any .md file
Documentation:
  - changed-files:
      - any-glob-to-any-file: ['src/routes/**', '**/*.md']

# Add 'DB' label to any changes within 'src/packages/db/' folder.
DB:
  - changed-files:
      - any-glob-to-any-file: ['src/packages/db/*']