name: MS Teams Deploy Card

on:
  workflow_run:
    workflows: [assign_reviewer]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print GITHUB_EVENT_PATH
        run: |
          cat "${GITHUB_EVENT_PATH}"
      - name: Extract Reviewers
        run: |
          REVIEWERS=$(jq -r '.pull_request.requested_reviewers[] | .login' "${GITHUB_EVENT_PATH}")
          echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV
      - uses: dchourasia/ms-teams-notification@1.0
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          show-on-exit: false
          allowed-file-len: 10
          timezone: IN
          custom-facts: |
            - name: Source Branch
              value: ${{ github.event.pull_request.head.ref }}
            - name: Target Branch
              value: ${{ github.event.pull_request.base.ref }}
            - name: Pull Request
              value: ${{ github.event.pull_request.html_url }}
            - name: Reviewers
              value: ${{ env.REVIEWERS }}
          custom-actions: |
            - text: View PR
              url: ${{ github.event.pull_request.html_url }}
