name: Sync Dev to Stage

on:
  push:
    branches:
      - dev

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Branches (Create PR)
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          FROM_BRANCH: 'dev'
          TO_BRANCH: 'stage'
          PULL_REQUEST_TITLE: "Sync dev to stage"
          PULL_REQUEST_BODY: "Automated PR to sync dev to stage."
          PULL_REQUEST_LABELS: "auto-merge"

  auto-merge:
    runs-on: ubuntu-latest
    needs: sync-branches

    steps:
      - name: Auto-Merge PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          target: minor
          merge-method: squash # Change to merge, squash, or rebase
          labels: auto-merge
          commit-title: "Auto-merged dev into stage"
          commit-message: "Automatically merged PR from dev to stage."
